site_name: Datasync Community Toolkit

theme:
  name: readthedocs
  highlightjs: true
  locale: en

nav:
  - Getting started: index.md
  - In depth:
    - Server:
      - The basics: in-depth/server/index.md
      - Databases:
        - Azure SQL: in-depth/server/db/azuresql.md
        - Cosmos: in-depth/server/db/cosmos.md
        - In Memory: in-depth/server/db/in-memory.md
        - LiteDb: in-depth/server/db/litedb.md
        - MongoDb: in-depth/server/db/mongodb.md
        - MySQL: in-depth/server/db/mysql.md
        - PgSQL: in-depth/server/db/pgsql.md
        - SQLite: in-depth/server/db/sqlite.md
      - OpenApi:
        - NSwag: in-depth/server/openapi/nswag.md
        - Swashbuckle: in-depth/server/openapi/swashbuckle.md
        - ".NET 9.x": in-depth/server/openapi/net9.md
    - Client:
      - The basics: in-depth/client/index.md
      - Authentication: in-depth/client/auth.md
      - Online operations: in-depth/client/online.md
      - Advanced topics:
        - MAUI AOT: in-depth/client/advanced/maui-aot.md
  - Samples:
      - Todo App:
        - The server: samples/todoapp/server.md
        - Avalonia: samples/todoapp/avalonia.md
        - MAUI: samples/todoapp/maui.md
        - WinUI3: samples/todoapp/winui3.md
        - WPF: samples/todoapp/wpf.md

markdown_extensions: 
  - toc:
      permalink: "#"
